// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Body        = require("./Body.js");
var React       = require("react");
var Header      = require("./Header.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

((require('./app.css')));

var component = ReasonReact.statelessComponent("App");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "App"
                }, ReasonReact.element(/* None */0, /* None */0, Header.make("Paul Rosset", /* array */[])), ReasonReact.element(/* None */0, /* None */0, Body.make(/* array */[])));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/*  Not a pure module */
