// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var KentPng     = require("./kent.png");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var EpitechPng  = require("./epitech.png");

((require('./Edu.css')));

var component = ReasonReact.statelessComponent("School");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("p", {
                  className: "text"
                }, "I'm currently studying at Epitech school, I also passed 1 year at Kent University for a Msc in Advanced computer science.", React.createElement("div", {
                      className: "schools"
                    }, React.createElement("img", {
                          className: "school",
                          src: EpitechPng
                        }), React.createElement("img", {
                          className: "school",
                          src: KentPng
                        })));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/*  Not a pure module */
