// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React          = require("react");
var ReasonReact    = require("reason-react/lib/js/src/ReasonReact.js");
var FrancePng      = require("./france.png");
var ReasonreactPng = require("./reasonreact.png");

((require('./Footer.css')));

var component = ReasonReact.statelessComponent("School");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "footer"
                }, React.createElement("q", {
                      className: "quote"
                    }, "Always be yourself unless you can be Batman then always be Batman !"), React.createElement("div", undefined, React.createElement("img", {
                          className: "country",
                          src: FrancePng
                        })), React.createElement("div", {
                      className: "developed"
                    }, React.createElement("img", {
                          className: "reason",
                          src: ReasonreactPng
                        }), "Proudly developed in ReasonReact"));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/*  Not a pure module */
