// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

((require('./Header.css')));

var component = ReasonReact.statelessComponent("Header");

function make(name, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("header", undefined, React.createElement("div", {
                      className: "container"
                    }, React.createElement("img", {
                          className: "profile",
                          src: "http://via.placeholder.com/150x150"
                        }), React.createElement("h3", undefined, name), React.createElement("div", {
                          className: "resume"
                        }, React.createElement("p", undefined, "Student developer, functional programing lover"), React.createElement("a", {
                              className: "icon twitter",
                              href: "polo"
                            }, React.createElement("i", {
                                  className: "fa fa-twitter"
                                })), React.createElement("a", {
                              className: "icon linkedin",
                              href: "polo"
                            }, React.createElement("i", {
                                  className: "fa fa-linkedin"
                                })), React.createElement("a", {
                              className: "icon github",
                              href: "polo"
                            }, React.createElement("i", {
                                  className: "fa fa-github"
                                })))));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/*  Not a pure module */
