// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var PaulJpg     = require("./paul.jpg");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

((require('./Header.css')));

var component = ReasonReact.statelessComponent("Header");

function make(name, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("header", undefined, React.createElement("div", {
                      className: "container"
                    }, React.createElement("img", {
                          className: "profile",
                          src: PaulJpg
                        }), React.createElement("h3", undefined, name), React.createElement("div", {
                          className: "resume"
                        }, React.createElement("p", {
                              className: "resume-profile"
                            }, "Student, Developer, Functional programming lover.", React.createElement("br", undefined), "Passionate about building things and share it.", React.createElement("br", undefined), "Thirsty of knowledge."), React.createElement("a", {
                              className: "icon twitter",
                              href: "https://www.twitter.com/RossetPaul"
                            }, React.createElement("i", {
                                  className: "fa fa-twitter"
                                })), React.createElement("a", {
                              className: "icon linkedin",
                              href: "https://www.linkedin.com/profile/view?id=AAIAABbpRe0B3A_Cmy2Ry3-cpt8i2AW51nCSLlo&amp;trk=nav_responsive_tab_profile_pic"
                            }, React.createElement("i", {
                                  className: "fa fa-linkedin"
                                })), React.createElement("a", {
                              className: "icon github",
                              href: "https://github.com/PaulRosset"
                            }, React.createElement("i", {
                                  className: "fa fa-github"
                                })), React.createElement("a", {
                              className: "icon email",
                              href: "mailto:paulrosset96@gmail.com"
                            }, React.createElement("i", {
                                  className: "fa fa-envelope"
                                })))));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/*  Not a pure module */
