// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

((require('./Body.css')));

var component = ReasonReact.statelessComponent("Parts");

function make(children) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "parts"
                }, children);
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/*  Not a pure module */
