// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var GfiPng      = require("./gfi.png");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var IndigenPng  = require("./indigen.png");
var TequilaPng  = require("./tequila.png");

((require('./Profesional.css')));

var component = ReasonReact.reducerComponent("Profesional");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (shelf) {
      return React.createElement("p", {
                  className: "text"
                }, "During the first 3 years at the school, I had the possibilities to be an intern in these companies:", React.createElement("br", undefined), React.createElement("div", {
                      className: "profesional"
                    }, React.createElement("div", {
                          className: "company"
                        }, React.createElement("img", {
                              className: "entreprise",
                              src: GfiPng,
                              onMouseEnter: (function () {
                                  return Curry._1(shelf[/* send */4], /* OnEnter */0);
                                }),
                              onMouseLeave: (function () {
                                  return Curry._1(shelf[/* send */4], /* OnLeave */1);
                                })
                            }), React.createElement("div", {
                              className: "date first",
                              style: {
                                display: shelf[/* state */2][/* show */2]
                              }
                            }, shelf[/* state */2][/* date */0])), React.createElement("div", {
                          className: "company"
                        }, React.createElement("img", {
                              className: "entreprise",
                              src: IndigenPng,
                              onMouseEnter: (function () {
                                  return Curry._1(shelf[/* send */4], /* OnEnter2 */2);
                                }),
                              onMouseLeave: (function () {
                                  return Curry._1(shelf[/* send */4], /* OnLeave2 */3);
                                })
                            }), React.createElement("div", {
                              className: "date second",
                              style: {
                                display: shelf[/* state */2][/* show2 */5]
                              }
                            }, shelf[/* state */2][/* date2 */3])), React.createElement("div", {
                          className: "company"
                        }, React.createElement("img", {
                              className: "entreprise",
                              src: TequilaPng,
                              onMouseEnter: (function () {
                                  return Curry._1(shelf[/* send */4], /* OnEnter3 */4);
                                }),
                              onMouseLeave: (function () {
                                  return Curry._1(shelf[/* send */4], /* OnLeave3 */5);
                                })
                            }), React.createElement("div", {
                              className: "date third",
                              style: {
                                display: shelf[/* state */2][/* show3 */8]
                              }
                            }, shelf[/* state */2][/* date3 */6]))));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[
              /* date */"From August to December 2015",
              /* showPopUp : false */0,
              /* show */"none",
              /* date2 */"From October 2016 to March 2017",
              /* showPopUp2 : false */0,
              /* show2 */"none",
              /* date3 */"From April 2017 to August 2017",
              /* showPopUp3 : false */0,
              /* show3 */"none"
            ];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      switch (action) {
        case 0 : 
            var newrecord = state.slice();
            return /* Update */Block.__(0, [(newrecord[/* showPopUp */1] = /* true */1, newrecord[/* show */2] = "block", newrecord)]);
        case 1 : 
            var newrecord$1 = state.slice();
            return /* Update */Block.__(0, [(newrecord$1[/* showPopUp */1] = /* false */0, newrecord$1[/* show */2] = "none", newrecord$1)]);
        case 2 : 
            var newrecord$2 = state.slice();
            return /* Update */Block.__(0, [(newrecord$2[/* showPopUp2 */4] = /* true */1, newrecord$2[/* show2 */5] = "block", newrecord$2)]);
        case 3 : 
            var newrecord$3 = state.slice();
            return /* Update */Block.__(0, [(newrecord$3[/* showPopUp2 */4] = /* false */0, newrecord$3[/* show2 */5] = "none", newrecord$3)]);
        case 4 : 
            var newrecord$4 = state.slice();
            return /* Update */Block.__(0, [(newrecord$4[/* showPopUp3 */7] = /* true */1, newrecord$4[/* show3 */8] = "block", newrecord$4)]);
        case 5 : 
            var newrecord$5 = state.slice();
            return /* Update */Block.__(0, [(newrecord$5[/* showPopUp3 */7] = /* false */0, newrecord$5[/* show3 */8] = "none", newrecord$5)]);
        
      }
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/*  Not a pure module */
