// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

((require('./school.css')));

var component = ReasonReact.statelessComponent("School");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("p", {
                  className: "text"
                }, "My name is Paul Rosset, I'm from the south of France.\n            I like creating and make the things great. I am among those who thinks that the perseverance is the key to succeed.", React.createElement("br", undefined), "Open source community is one of my favorite things.");
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/*  Not a pure module */
