// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var KentPng     = require("./kent.png");
var OpenPng     = require("./open.png");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

((require('./Sidebar.css')));

var component = ReasonReact.statelessComponent("SideBar");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "sidebar-container"
                }, "Project I'm working on:", React.createElement("div", {
                      className: "project"
                    }, React.createElement("img", {
                          className: "source",
                          src: OpenPng
                        })), React.createElement("div", {
                      className: "project"
                    }, React.createElement("img", {
                          className: "kent",
                          src: KentPng
                        })));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/*  Not a pure module */
